spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3307/transportador?serverTimezone=UTC&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
